-- 1. Total revenue generated by each country 
select country, sum(quantity * unit_price) as total_sales
from ecommerce_data$
group by country
order by total_sales DESC;

-- 2. Top 5 products by quantity sold
select top 5
product_name, sum(quantity) as total_quantity_sales
from ecommerce_data$
group by product_name
order by total_quantity_sales DESC;

-- 3. Monthly sales totals
select
FORMAT(order_date,'MMM-yy') as month,
sum(quantity * unit_price) as monthly_sales
from ecommerce_data$
group by format(order_date,'MMM-yy')
order by month;

-- 4. Revenue by each product category
select product_category, sum(quantity * unit_price) as Total_sales
from ecommerce_data$
group by product_category
order by Total_sales DESC;

-- 5.  Average Order Value by Product 
select product_name, AVG(quantity * unit_price) as Avg_order_value
from ecommerce_data$
group by product_name
order by Avg_order_value ASC;

-- 6. Count of orders by Product category
-- Count of all orders
select product_category,
COUNT(distinct order_id) as Total_Orders
from ecommerce_data$
group by product_category
order by Total_Orders;

-- 7. Count of unique customers
select COUNT(distinct order_id) as unique_customer
from ecommerce_data$;

-- 8. Countries with highest number of orders
select country, count(distinct order_id) as number_of_orders
from ecommerce_data$
group by country
order by number_of_orders DESC;

-- 9. Product with highest total revenue
select top 1
product_name, sum(quantity * unit_price) as Total_Revenue
from ecommerce_data$
group by product_name
order by Total_Revenue DESC;

-- 10. Daily sales trend
select CAST(order_date as date) as date,
sum(quantity * unit_price) as Daily_Sales
from ecommerce_data$
group by CAST(order_date as date)
order by date ASC;





